### ISSUE TITLE
Feature request: Take into account altitude for computation of sunrise/sunset ...

### ISSUE THREAD

**Issue by thomasbee** [mourner/suncalc#104]
Hi Vladimir,

I am using your great little lib to compute sunrise/sunset etc for the VLT telescopes of the Paranal observatory which is located at approx. 2600m altitude. Your computations are a few minutes off, because at that altitude obviously the sun sets later and rises earlier. 

It would be nice if you took altitude into account.

**Comment by mourner** [comment]
Unfortunately I don't know how to do that. But contributions are always welcome!

**Comment by mitochondriac** [comment]
I believe you could determine the added declination angle (how much more you look "down" to the horizon from your altitude) by calculating the angle down to the earth's tangent fairly simply.  Of course the accuracy is only as good as the sea level estimate of the earth's radius.

Additional declination = 90 - asin(radius of earth/(altitude + radius of earth))
Additional declination = 90 - asin(6,371,000m/(altitude + 6,371,000m))

![image](https://user-images.githubusercontent.com/39555227/40420290-f5d4c98c-5e55-11e8-8508-69a459828ea0.png)

**Comment by ryanp54** [comment]
To make this change we need to adjust the **h** argument that is passed in to the hourAngle function. Mitochondriac's adjustment is a good starting place, but it does not take into account the additional refraction that takes place.

The website listed in the README as the source of the equations used provides an approximation for the effect of the additional refraction, but I feel like I must be missing something because it does not make sense to me. It only depends on the latitude and declination of the sun, not the observer altitude. Additionally, it gives zero extra refraction at the equator on the equinoxes, which seems nonsensical.

I found a method on Wikipedia to approximately adjust for both effects that is based only on the observer altitude:

![image](https://user-images.githubusercontent.com/14948859/71310761-58a25680-23dd-11ea-92a4-0e2e5eb48585.png)

I cannot find a source for this, but employing this adjustment gives results that are consist with sunset time calculators I have found online. It is also the method used in this project:

https://www.mathworks.com/matlabcentral/fileexchange/64692-sunrise-sunrise-and-sunset-times

I plan on implementing this and submitting a pull request this week.
