### ISSUE TITLE
Moon rise and moon set time?

### ISSUE THREAD

**Issue by dinhnhat0401** [mourner/suncalc#7]
Many thanks for this helpful library. 
How can i implement code to calculate the moon rise and moon set time?

**Comment by DouglasAllen** [comment]
I've been working on a solution. I use a C extension that includes the libastro-3.7.7 C code from pyephem. That may not be kosher for some but it's just an experiment and so far I'm getting good results for things like right ascension, ecliptic longitude, and declination. The only problem is that riset.c yields times in LST not UTC. I'm experimenting with that now too and why I'm here because I went looking for something to verify the times I am getting. Plenty of online stuff like https://theskylive.com/guide which is prtty awesome.
